### ISSUE TITLE
How to integrate in nuxt

### ISSUE THREAD

**Issue by anjali89r** [zh-rocco/vue-photoswipe-directive#3]
In order to make it client-only (to avoid the reference error: window is not defined), I did as follows:

`yarn add photoswipe`
`yarn add vue-photoswipe-directive`

1. Created a file inside plugins folder, for example, directives.js: 

` import Vue from 'vue'`
`import createPreviewDirective from 'vue-photoswipe-directive'`

`Vue.directive('preview', createPreviewDirective())`

2. In **nuxt.config.js** add something like plugins: `[{ src: '~/plugins/directives', mode: 'client' }]`
3. used in **component.vue** : 
`<img v-preview src="path/to/image.jpg" alt="image" />`

All works well on initial page load. But on the page reload it doesn't work causing the error:

![Screen Shot 2020-07-24 at 12 29 56 PM](https://user-images.githubusercontent.com/30242582/88413590-6d96fc00-cda9-11ea-8013-3ff92d6e38c9.png)

**Comment by didkan** [comment]
I got it working by providing `PhotoSwipe` and `PhotoSwipeUI` to the directive.

```
import PhotoSwipe from 'photoswipe/dist/photoswipe'
import PhotoSwipeUI from 'photoswipe/dist/photoswipe-ui-default'
import 'photoswipe/dist/photoswipe.css'
import 'photoswipe/dist/default-skin/default-skin.css'
import createPreviewDirective from "vue-photoswipe-directive";

export default {
  directives: {
    preview: createPreviewDirective({
      // Photoswipe options
    }, PhotoSwipe, PhotoSwipeUI)
  }
}
```

**Comment by anjali89r** [comment]
Thanks, @didkan ! That fixed the issue :)

**Comment by didkan** [comment]
I found it going through the source, but it should probably be added to the docs/instructions.
@zh-rocco
